### ISSUE TITLE
About the checkpoint

### ISSUE THREAD

**Issue by HLSvois** [cpystan/WSI-VQA#1]
Hi,

Thank you for sharing your amazing work on this project! 

I was wondering if you have any plans to release the trained model checkpoint? I noticed that there is currently no way to download the checkpoint of WSI-VQA.

Thank you in advance and looking forward your answers!

**Comment by cpystan** [comment]
Yes, we will release the ckpt later.

**Comment by HLSvois** [comment]
That's great! Thanks for your response.
