### ISSUE TITLE
the Data Filtering Details

### ISSUE THREAD

**Issue by lsnls** [cpystan/WSI-VQA#6]
Hi, authors!

Thank you for your pioneering work! In the `Data Curation` section of your paper, you mentioned discarding some pairs. In specific, in the close-ended subset, pairs with significant defects and pairs where answers cannot be inferred from WSIs are removed. In the open-ended subset, pairs where clinical indexes cannot be inferred from WSIs are removed. I am curious about the operation used to remove these pairs. Was it a model-based automated process or a manual check?

Looking forward to your reply. Many thanks!

Best Regards,
Suoni

**Comment by cpystan** [comment]
Manual check. Additianally with ome rule-based NLP process.

**Comment by lsnls** [comment]
Thank you so much!
