### ISSUE TITLE
how to extract keywords and corresponding values

### ISSUE THREAD

**Issue by lsnls** [cpystan/WSI-VQA#7]
Hi, authors!

Thanks for your valuable work! In the `Data Generation` section of your paper, you mentioned `extracting keywords to fit templates from the clinical files in TCGA`. I am curious about  what specific methods you used to extract keywords and their corresponding values?

I am looking forward to your reply. Thanks a lot.

Best regards,
Suoni

**Comment by cpystan** [comment]
Excel files in TCGA. It has key-value pairs naturally.

**Comment by lsnls** [comment]
Thanks for your quick response! That helps me a lot!
