### ISSUE TITLE
confusion about training a text extractor from scratch

### ISSUE THREAD

**Issue by lsnls** [cpystan/WSI-VQA#8]
Hi, authors!

Thank you for your exciting work! I am confused about what architecture was used for the text extractor training from scratch? And why is it feasible to train a text extractor from scratch when the length of word tokens is small? I guess that it may be because you can choose a network with fewer parameters to extract proper text features when the length of word tokens is small, isn't it?

Thank you!

Best regards,
Suoni

**Comment by cpystan** [comment]
You are right. Small data, so it is better to train from scratch.

**Comment by lsnls** [comment]
Thank you. I read your source code, and I found that the text extractor has no operation when training from scratch. So you just use the `Embedding` layer to fit the text features, isn't it?

**Comment by cpystan** [comment]
Yes,that's it.

**Comment by lsnls** [comment]
Thank you.
